# Generated by Django 3.1.5 on 2021-07-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210711_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='default_avatar',
            field=models.ImageField(blank=True, default='default/default_avatar.png', null=True, upload_to='default/'),
        ),
    ]
