# Generated by Django 3.1.5 on 2021-07-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210711_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='default_avatar',
            field=models.ImageField(blank=True, default='default/default_avatar.png', null=True, upload_to=''),
        ),
    ]
